# One index for every container's log lines. Two weeks or 5 GB, whichever comes first, so a
# laptop doesn't fill up; size it to the licence and retention policy in production.
[darviq_logs]
homePath = $SPLUNK_DB/darviq_logs/db
coldPath = $SPLUNK_DB/darviq_logs/colddb
thawedPath = $SPLUNK_DB/darviq_logs/thaweddb
frozenTimePeriodInSecs = 1209600
maxTotalDataSizeMB = 5000
